### ISSUE TITLE
Flash not working with Firefox

### ISSUE THREAD

**Issue by xuanngo2001** [xuanngo2001/cust-live-deb#243]
`apt install browser-plugin-freshplayer-pepperflash pepperflashplugin-nonfree`

**Comment by limelime** [comment]
https://wiki.debian.org/PepperFlashPlayer/Installing

**Comment by limelime** [comment]
https://unix.stackexchange.com/a/276351

**Comment by xuanngo2001** [comment]
Adobe officially stopped supporting Flash in 2021 and has blocked Flash content from running in Flash Player.
Web browsers have removed all Flash-related software.
